---
- name: create tower folder
  file:
    path: /home/admin/ansible
    state: directory
- name: copy over playbook
  copy:
    src: "{{ item.src }}" 
    dest: /home/admin/ansible
    owner: admin
    group: admin
  loop:
    - src: files/update.yml
      dest: update.yml
    - src: files/ansible.cfg
      dest: ansible.cfg
    - src: files/inventory
      dest: inventory
- name: run the playbook 
  shell: nohup ansible-playbook update.yml </dev/null >/dev/null 2>&1 &
  args: 
    chdir: /home/admin/ansible/

