---
- name: create tower folder
  file:
    path: /home/admin/ansible
    state: directory
- name: copy over playbook
  copy:
    src: "{{ item.src }}" 
    dest: /home/admin/ansible
    owner: admin
    group: admin
  loop:
    - src: files/update.yml
      dest: update.yml
    - src: files/ansible.cfg
      dest: ansible.cfg
    - src: files/inventory
      dest: inventory
- name: copy over command
  copy:
    src: files/command.sh
    dest: /home/admin/ansible
    owner: admin
    group: admin
    mode: 0755
- name: run the playbook 
  command: nohup ./command.sh
  args:
    chrdir: /home/admin/ansible/
   
      # shell: nohup ansible-playbook update.yml </dev/null >/dev/null 2>&1 &

