---
- name: copy over playbook
  copy:
    src: "{{ item }}" 
    dest: /home/kyetter/irs/AnsiblePOC/execution/
    owner: kyetter
    group: kyetter
  loop:
    - files/update.yml
    - files/ansible.cfg
    - files/inventory
- name: run the playbook 
  command: ansible-playbook update.yml
  args: 
    chdir: /home/kyetter/irs/AnsiblePOC/execution/

