---
- name: copy over playbook
  copy:
    src: 
      - files/update.yml
      - files/ansible.cfg
      - files/inventory
    dest: /home/kyetter/irs/AnsiblePOC/execution/
    owner: kyetter
    group: kyetter

- name: run the playbook 
  command: ansible-playbook update.yml
    args: 
      chdir: /home/kyetter/irs/AnsiblePOC/execution/ansible-playbook/

