---
- name: copy over playbook
  copy:
    src: "{{ item.src }}" 
    dest: /home/kyetter/irs/AnsiblePOC/execution/{{item.dest}}
    owner: kyetter
    group: kyetter
  loop:
    - src: files/update.yml
      dest: update.yml
    - src: files/ansible.cfg
      dest: ansible.cfg
    - src: files/inventory
      dest: inventory
- name: run the playbook 
  shell: nohup ansible-playbook update.yml &
  args: 
    chdir: /home/kyetter/irs/AnsiblePOC/execution/

