---
- name: create project
  hosts: all 
  tasks:
    - name: make sure tower-cli is installed
      pip:
        name: ansible-tower-cli
        state: present
      become: yes
          #    - name: set up ansible tower cli configs
          #command: tower-cli config host https://192.168.122.5/
    - name: create project
      tower_project:
        name: "{{ name }}"
        description: "{{ description }}"
        organization: "{{ organization }}"
        state: present
        validate_certs: false
    - name: give user ownership to project
      tower_role:
        user: "{{tower_user_id}}"
        role: admin
        projects: "{{ name}}"
        state: present
