---
- name: create project
  hosts: all 
  tasks:
    - name: create project
      tower_project:
        name: "{{ name }}"
        description: "{{ description }}"
        organization: "{{ organization }}"
        state: present
        validate_certs: false
