---
- name: use a secret
  hosts: all
  become: yes
  tasks:
    - set_fact:
        endpoint_filename: "/tmp/endpoint-vars-{{ lookup('pipe', 'date +\"%s\"') }}.yml"
    
    - name: download the endpoint
      get_url:
        url: https://raw.githubusercontent.com/kyetter/TowerPatchPOC/main/vars.yml 
        dest: "{{endpoint_filename}}"
          
    - name: include the secret
      include_vars: 
        file: "{{endpoint_filename}}"
    - name: print secret
      debug:
        var: secret

    - name: cleanup vars
      file:
        state: absent
        path: "{{ endpoint_filename }}"
