---
- name: update ansible tower servers
  hosts: 192.168.122.5
  remote_user: kyetter
  tasks:
    - name: dnf update
      become: yes
      dnf:
        name: '*'
        state: latest
        skip_broken: yes

    - name: reboot server
      become: yes
      reboot:

    - name: check OS
      command: cat /etc/os-release
      register: OSversion

    - name: print out OS version
      debug:
        var: OSversion

    - name: make sure ansible is up
      become: yes
      systemd:
        name: ansible-tower
        state: started
        enabled: yes

    - name: start final job on tower
      uri:
        url: https://192.168.122.5/api/v2/job_templates/Demo%20Job%20Template/launch/
        method: POST
        validate_certs: no
        force_basic_auth: yes  
        status_code: 
          - 200
          - 201
        user: admin
        password: babysavannah

